### ISSUE TITLE
Developing Grafana Widget

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-widgets#14]
Hi,
We are developing a widget named **"GrafanaWidget"** Which can provide us with different types of charts (AreaChart, BarChart, Gauge, SingleStat), using Grafana data. 
Sample widgets and setting dialog is shown in below snapshot picture:

![Screenshot from 2020-10-20 14-19-07](https://user-images.githubusercontent.com/70196035/96578631-58ffcc80-12e2-11eb-979f-0611572133f8.png)

Since we are approaching to finish **GrafanaWidget** development, and we plan to contribute it in Osjs project, we would be happy if you leave any comment on it.

**Comment by mahsashadi** [comment]
Hi, we have finished developing of **GrafanaWidget** .

Here is the github repository link:
https://github.com/BurnaSmartLab/osjs-grafana-widget

**Comment by mahsashadi** [comment]
pull request: https://github.com/os-js/manual.os-js.org/pull/32

**Comment by andersevenrud** [comment]
Merged :)
