### ISSUE TITLE
Change position of widgets by desktop resizing

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-widgets#15]
When the Osjs desktop is **resized**, the **position** of widgets remained fixed and they can be disappeard from desktop untill moving them. 
I need the widget position to be changed dynamically by resizing the desktop.

**Comment by andersevenrud** [comment]
Ref: https://github.com/os-js/osjs-client/issues/135

**Comment by andersevenrud** [comment]
I'll try to have a look at this tomorrow :)

**Comment by mahsashadi** [comment]
Hi  :)
Did you have any time to work on this issue?

**Comment by andersevenrud** [comment]
Sorry, but work took over.

I'll probably have it done this weekend :crossed_fingers:

**Comment by andersevenrud** [comment]
I finally had some time to look at this.

PR: https://github.com/os-js/osjs-widgets/pull/16/files

Going to merge this ASAP.

**Comment by andersevenrud** [comment]
This is now in the `3.1.0` version of `@osjs/widgets`. It is ebabled with the same config setting as the changes in `@osjs/client` (at least for now).

Let me know how it works out :)

**Comment by mahsashadi** [comment]
Thank you :)
Widget positions are now changing by desktop resizing :+1:
