### ISSUE TITLE
keep widget fixed in the upper right corner

### ISSUE THREAD

**Issue by yoyosaygood** [os-js/osjs-widgets#19]
I hope my widget fixed in the upper right corner(It's best not allowed to move and hide if ),how can i do this?

**Comment by andersevenrud** [comment]
It's been very long since I used this, but I think you can do this in your widget:

```
  constructor(core, options) {
    super(core, options, {
      dimension: {
        width: 300,
        height: 50
      },
      position: {
        top: 100,
        right: 100
      }
    }, { });
  }
```

However this will probably still allow the user to move it. If you want to be able to lock this then a new feature is needed here (which would be very simple to implement).

**Comment by andersevenrud** [comment]
Closing this because of lack of response.
